name = "hydrexmain"
main = ".open-next/worker.js"
compatibility_date = "2026-03-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[vars]
NEXT_PUBLIC_APP_NAME = "Urbex Dashboard"
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyDqByh59Q6fUQfJdKWui-5mC2TrhjFxkZ0"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "hydrex-8e0bb.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "hydrex-8e0bb"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "hydrex-8e0bb.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "2560035280"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:2560035280:web:6246d4353cb5c6843811d5"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-WDBLBE4P99"